using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LotroCalc.RecipeData.Professions;

namespace LotroCalc.RecipeData.Ingredients.CompositeIngredients.Tailor._3_Expert
{
    public abstract class ExpertIngredients : TailorIngredients 
    {
        protected ExpertIngredients()
        {
            Tier = ProfessionTierEnum.Expert;
        }

        public static void GetIngredients(ref SortedDictionary<string, Ingredient> dict)
        {
            dict.Add(BasicBurglarTools.DisplayName, new BasicBurglarTools(1));
            dict.Add(CommonerHeraldArmaments.DisplayName, new CommonerHeraldArmaments(1));
            dict.Add(CottonArmour.DisplayName, new CottonArmour(1));
            dict.Add(CottonCap.DisplayName, new CottonCap(1));
            dict.Add(CottonCloak.DisplayName, new CottonCloak(1));
            dict.Add(CottonGloves.DisplayName, new CottonGloves(1));
            dict.Add(CottonLeggings.DisplayName, new CottonLeggings(1));
            dict.Add(CottonRobe.DisplayName, new CottonRobe(1));
            dict.Add(CottonShoes.DisplayName, new CottonShoes(1));
            dict.Add(CottonShoulderGuards.DisplayName, new CottonShoulderGuards(1));
            dict.Add(DwarfmakeCottonArmour.DisplayName, new DwarfmakeCottonArmour(1));
            dict.Add(DwarfmakeCottonGloves.DisplayName, new DwarfmakeCottonGloves(1));
            dict.Add(DwarfmakeCottonLeggings.DisplayName, new DwarfmakeCottonLeggings(1));
            dict.Add(DwarfmakeCottonShoes.DisplayName, new DwarfmakeCottonShoes(1));
            dict.Add(DwarfmakeCottonShoulderGuards.DisplayName, new DwarfmakeCottonShoulderGuards(1));
            dict.Add(DwarfmakeOutridersArmour.DisplayName, new DwarfmakeOutridersArmour(1));
            dict.Add(DwarfmakeOutridersBoots.DisplayName, new DwarfmakeOutridersBoots(1));
            dict.Add(DwarfmakeOutridersGloves.DisplayName, new DwarfmakeOutridersGloves(1));
            dict.Add(DwarfmakeOutridersLeggings.DisplayName, new DwarfmakeOutridersLeggings(1));
            dict.Add(DwarfmakeOutridersShoulderGuards.DisplayName, new DwarfmakeOutridersShoulderGuards(1));
            dict.Add(DwarfmakeTravellersArmour.DisplayName, new DwarfmakeTravellersArmour(1));
            dict.Add(DwarfmakeTravellersGloves.DisplayName, new DwarfmakeTravellersGloves(1));
            dict.Add(DwarfmakeTravellersLeggings.DisplayName, new DwarfmakeTravellersLeggings(1));
            dict.Add(DwarfmakeTravellersShoes.DisplayName, new DwarfmakeTravellersShoes(1));
            dict.Add(DwarfmakeTravellersShoulderGuards.DisplayName, new DwarfmakeTravellersShoulderGuards(1));
            dict.Add(ElvenCottonArmour.DisplayName, new ElvenCottonArmour(1));
            dict.Add(ElvenCottonGloves.DisplayName, new ElvenCottonGloves(1));
            dict.Add(ElvenCottonLeggings.DisplayName, new ElvenCottonLeggings(1));
            dict.Add(ElvenCottonShoes.DisplayName, new ElvenCottonShoes(1));
            dict.Add(ElvenCottonShoulderGuards.DisplayName, new ElvenCottonShoulderGuards(1));
            dict.Add(ElvenOutridersLeggings.DisplayName, new ElvenOutridersLeggings(1));
            dict.Add(ElvenOutridersArmour.DisplayName, new ElvenOutridersArmour(1));
            dict.Add(ElvenOutridersBoots.DisplayName, new ElvenOutridersBoots(1));
            dict.Add(ElvenOutridersGloves.DisplayName, new ElvenOutridersGloves(1));
            dict.Add(ElvenOutridersShoulderGuards.DisplayName, new ElvenOutridersShoulderGuards(1));
            dict.Add(ElvenProspectorsPack.DisplayName, new ElvenProspectorsPack(1));
            dict.Add(ElvenTravellersArmour.DisplayName, new ElvenTravellersArmour(1));
            dict.Add(ElvenTravellersGloves.DisplayName, new ElvenTravellersGloves(1));
            dict.Add(ElvenTravellersLeggings.DisplayName, new ElvenTravellersLeggings(1));
            dict.Add(ElvenTravellersShoes.DisplayName, new ElvenTravellersShoes(1));
            dict.Add(ElvenTravellersShoulderGuards.DisplayName, new ElvenTravellersShoulderGuards(1));
            dict.Add(EmbossedLeatherBrace.DisplayName, new EmbossedLeatherBrace(1));
            dict.Add(ExquisiteOutridersArmourGuild.DisplayName, new ExquisiteOutridersArmourGuild(1));
            dict.Add(ExquisiteOutridersGlovesGuild.DisplayName, new ExquisiteOutridersGlovesGuild(1));
            dict.Add(ExquisiteOutridersHelmGuild.DisplayName, new ExquisiteOutridersHelmGuild(1));
            dict.Add(ExquisiteOutridersLeggingsGuild.DisplayName, new ExquisiteOutridersLeggingsGuild(1));
            dict.Add(ExquisiteOutridersShoesGuild.DisplayName, new ExquisiteOutridersShoesGuild(1));
            dict.Add(ExquisiteOutridersShoulderGuardsGuild.DisplayName, new ExquisiteOutridersShoulderGuardsGuild(1));
            dict.Add(ExquisiteTravellersArmourGuild.DisplayName, new ExquisiteTravellersArmourGuild(1));
            dict.Add(ExquisiteTravellersCloakGuild.DisplayName, new ExquisiteTravellersCloakGuild(1));
            dict.Add(ExquisiteTravellersGlovesGuild.DisplayName, new ExquisiteTravellersGlovesGuild(1));
            dict.Add(ExquisiteTravellersHatGuild.DisplayName, new ExquisiteTravellersHatGuild(1));
            dict.Add(ExquisiteTravellersLeggingsGuild.DisplayName, new ExquisiteTravellersLeggingsGuild(1));
            dict.Add(ExquisiteTravellersRobeGuild.DisplayName, new ExquisiteTravellersRobeGuild(1));
            dict.Add(ExquisiteTravellersShoesGuild.DisplayName, new ExquisiteTravellersShoesGuild(1));
            dict.Add(ExquisiteTravellersShoulderGuardsGuild.DisplayName, new ExquisiteTravellersShoulderGuardsGuild(1));
            dict.Add(FinelyStitchedBackpack.DisplayName, new FinelyStitchedBackpack(1));
            dict.Add(FinelyWovenStandardOfVictory.DisplayName, new FinelyWovenStandardOfVictory(1));
            dict.Add(FinelyWovenExpertStandardofHope.DisplayName, new FinelyWovenExpertStandardofHope(1));
            dict.Add(FinelyWovenExpertStandardofWar.DisplayName, new FinelyWovenExpertStandardofWar(1));
            dict.Add(FineWoodcuttersPack.DisplayName, new FineWoodcuttersPack(1));
            dict.Add(HeavyCottonArmour.DisplayName, new HeavyCottonArmour(1));
            dict.Add(HeavyCottonCloak.DisplayName, new HeavyCottonCloak(1));
            dict.Add(HeavyCottonGloves.DisplayName, new HeavyCottonGloves(1));
            dict.Add(HeavyCottonHat.DisplayName, new HeavyCottonHat(1));
            dict.Add(HeavyCottonLeggings.DisplayName, new HeavyCottonLeggings(1));
            dict.Add(HeavyCottonRobe.DisplayName, new HeavyCottonRobe(1));
            dict.Add(HeavyCottonShoes.DisplayName, new HeavyCottonShoes(1));
            dict.Add(HeavyCottonShoulderGuards.DisplayName, new HeavyCottonShoulderGuards(1));
            dict.Add(HeavyDwarfmakeCottonArmour.DisplayName, new HeavyDwarfmakeCottonArmour(1));
            dict.Add(HeavyDwarfmakeCottonGloves.DisplayName, new HeavyDwarfmakeCottonGloves(1));
            dict.Add(HeavyDwarfmakeCottonLeggings.DisplayName, new HeavyDwarfmakeCottonLeggings(1));
            dict.Add(HeavyDwarfmakeCottonShoes.DisplayName, new HeavyDwarfmakeCottonShoes(1));
            dict.Add(HeavyDwarfmakeCottonShoulderGuards.DisplayName, new HeavyDwarfmakeCottonShoulderGuards(1));
            dict.Add(HeavyElvenCottonArmour.DisplayName, new HeavyElvenCottonArmour(1));
            dict.Add(HeavyElvenCottonGloves.DisplayName, new HeavyElvenCottonGloves(1));
            dict.Add(HeavyElvenCottonLeggings.DisplayName, new HeavyElvenCottonLeggings(1));
            dict.Add(HeavyElvenCottonShoes.DisplayName, new HeavyElvenCottonShoes(1));
            dict.Add(HeavyElvenCottonShoulderGuards.DisplayName, new HeavyElvenCottonShoulderGuards(1));
            dict.Add(ImprovedEmbossedLeatherBraceGuild.DisplayName, new ImprovedEmbossedLeatherBraceGuild(1));
            dict.Add(ImprovedReinforcedLeatherPadGuild.DisplayName, new ImprovedReinforcedLeatherPadGuild(1));
            dict.Add(ImprovedSturdyLeatherBindingGuild.DisplayName, new ImprovedSturdyLeatherBindingGuild(1));
            dict.Add(ImprovedSturdyLeatherGuardGuild.DisplayName, new ImprovedSturdyLeatherGuardGuild(1));
            dict.Add(MaidatarmsHeraldArmaments.DisplayName, new MaidatarmsHeraldArmaments(1));
            dict.Add(ManatArmsHeraldArmaments.DisplayName, new ManatArmsHeraldArmaments(1));
            dict.Add(MediumExpertPatternGuild.DisplayName, new MediumExpertPatternGuild(1));
            dict.Add(OutridersArmour.DisplayName, new OutridersArmour(1));
            dict.Add(OutridersGloves.DisplayName, new OutridersGloves(1));
            dict.Add(OutridersHelm.DisplayName, new OutridersHelm(1));
            dict.Add(OutridersLeggings.DisplayName, new OutridersLeggings(1));
            dict.Add(OutridersShoes.DisplayName, new OutridersShoes(1));
            dict.Add(OutridersShoulderGuards.DisplayName, new OutridersShoulderGuards(1));
            dict.Add(PilgrimHeraldArmaments.DisplayName, new PilgrimHeraldArmaments(1));
            dict.Add(ReinforcedLeatherPad.DisplayName, new ReinforcedLeatherPad(1));
            dict.Add(ReinforcedSturdyDwarfmakeLeatherArmour.DisplayName, new ReinforcedSturdyDwarfmakeLeatherArmour(1));
            dict.Add(ReinforcedSturdyDwarfmakeLeatherBoots.DisplayName, new ReinforcedSturdyDwarfmakeLeatherBoots(1));
            dict.Add(ReinforcedSturdyDwarfmakeLeatherGloves.DisplayName, new ReinforcedSturdyDwarfmakeLeatherGloves(1));
            dict.Add(ReinforcedSturdyDwarfmakeLeatherLeggings.DisplayName, new ReinforcedSturdyDwarfmakeLeatherLeggings(1));
            dict.Add(ReinforcedSturdyDwarfmakeLeatherShoulderGuards.DisplayName, new ReinforcedSturdyDwarfmakeLeatherShoulderGuards(1));
            dict.Add(ReinforcedSturdyElvenLeatherArmour.DisplayName, new ReinforcedSturdyElvenLeatherArmour(1));
            dict.Add(ReinforcedSturdyElvenLeatherBoots.DisplayName, new ReinforcedSturdyElvenLeatherBoots(1));
            dict.Add(ReinforcedSturdyElvenLeatherGloves.DisplayName, new ReinforcedSturdyElvenLeatherGloves(1));
            dict.Add(ReinforcedSturdyElvenLeatherLeggings.DisplayName, new ReinforcedSturdyElvenLeatherLeggings(1));
            dict.Add(ReinforcedSturdyElvenLeatherShoulderGuards.DisplayName, new ReinforcedSturdyElvenLeatherShoulderGuards(1));
            dict.Add(ReinforcedSturdyLeatherArmour.DisplayName, new ReinforcedSturdyLeatherArmour(1));
            dict.Add(ReinforcedSturdyLeatherGloves.DisplayName, new ReinforcedSturdyLeatherGloves(1));
            dict.Add(ReinforcedSturdyLeatherHelm.DisplayName, new ReinforcedSturdyLeatherHelm(1));
            dict.Add(ReinforcedSturdyLeatherLeggings.DisplayName, new ReinforcedSturdyLeatherLeggings(1));
            dict.Add(ReinforcedSturdyLeatherShoes.DisplayName, new ReinforcedSturdyLeatherShoes(1));
            dict.Add(ReinforcedSturdyLeatherShoulderGuards.DisplayName, new ReinforcedSturdyLeatherShoulderGuards(1));
            dict.Add(ScholarsRunesatchelofDagor.DisplayName, new ScholarsRunesatchelofDagor(1));
            dict.Add(ScholarsRunesatchelofNestad.DisplayName, new ScholarsRunesatchelofNestad(1));
            dict.Add(ScholarsRunesatchelofThalas.DisplayName, new ScholarsRunesatchelofThalas(1));
            dict.Add(ShieldMaidenHeraldArmaments.DisplayName, new ShieldMaidenHeraldArmaments(1));
            dict.Add(SmallExpertPatternGuild.DisplayName, new SmallExpertPatternGuild(1));
            dict.Add(SmallRingandLeafRug.DisplayName, new SmallRingandLeafRug(1));
            dict.Add(SquireHeraldArmaments.DisplayName, new SquireHeraldArmaments(1));
            dict.Add(SturdyDwarfmakeLeatherArmour.DisplayName, new SturdyDwarfmakeLeatherArmour(1));
            dict.Add(SturdyDwarfmakeLeatherBoots.DisplayName, new SturdyDwarfmakeLeatherBoots(1));
            dict.Add(SturdyDwarfmakeLeatherGloves.DisplayName, new SturdyDwarfmakeLeatherGloves(1));
            dict.Add(SturdyDwarfmakeLeatherLeggings.DisplayName, new SturdyDwarfmakeLeatherLeggings(1));
            dict.Add(SturdyDwarfmakeLeatherShoulderGuards.DisplayName, new SturdyDwarfmakeLeatherShoulderGuards(1));
            dict.Add(SturdyElvenLeatherArmour.DisplayName, new SturdyElvenLeatherArmour(1));
            dict.Add(SturdyElvenLeatherBoots.DisplayName, new SturdyElvenLeatherBoots(1));
            dict.Add(SturdyElvenLeatherGloves.DisplayName, new SturdyElvenLeatherGloves(1));
            dict.Add(SturdyElvenLeatherLeggings.DisplayName, new SturdyElvenLeatherLeggings(1));
            dict.Add(SturdyElvenLeatherShoulderGuards.DisplayName, new SturdyElvenLeatherShoulderGuards(1));
            dict.Add(SturdyLeatherArmour.DisplayName, new SturdyLeatherArmour(1));
            dict.Add(SturdyLeatherBinding.DisplayName, new SturdyLeatherBinding(1));
            dict.Add(SturdyLeatherGloves.DisplayName, new SturdyLeatherGloves(1));
            dict.Add(SturdyLeatherGuard.DisplayName, new SturdyLeatherGuard(1));
            dict.Add(SturdyLeatherHelm.DisplayName, new SturdyLeatherHelm(1));
            dict.Add(SturdyLeatherLeggings.DisplayName, new SturdyLeatherLeggings(1));
            dict.Add(SturdyLeatherShoes.DisplayName, new SturdyLeatherShoes(1));
            dict.Add(SturdyLeatherShoulderGuards.DisplayName, new SturdyLeatherShoulderGuards(1));
            dict.Add(SuperbDwarfmakeOutridersArmour.DisplayName, new SuperbDwarfmakeOutridersArmour(1));
            dict.Add(SuperbDwarfmakeOutridersBoots.DisplayName, new SuperbDwarfmakeOutridersBoots(1));
            dict.Add(SuperbDwarfmakeOutridersGloves.DisplayName, new SuperbDwarfmakeOutridersGloves(1));
            dict.Add(SuperbDwarfmakeOutridersLeggings.DisplayName, new SuperbDwarfmakeOutridersLeggings(1));
            dict.Add(SuperbDwarfmakeOutridersShoulderGuards.DisplayName, new SuperbDwarfmakeOutridersShoulderGuards(1));
            dict.Add(SuperbDwarfmakeTravellersArmour.DisplayName, new SuperbDwarfmakeTravellersArmour(1));
            dict.Add(SuperbDwarfmakeTravellersGloves.DisplayName, new SuperbDwarfmakeTravellersGloves(1));
            dict.Add(SuperbDwarfmakeTravellersLeggings.DisplayName, new SuperbDwarfmakeTravellersLeggings(1));
            dict.Add(SuperbDwarfmakeTravellersShoes.DisplayName, new SuperbDwarfmakeTravellersShoes(1));
            dict.Add(SuperbDwarfmakeTravellersShoulderGuards.DisplayName, new SuperbDwarfmakeTravellersShoulderGuards(1));
            dict.Add(SuperbElvenOutridersArmour.DisplayName, new SuperbElvenOutridersArmour(1));
            dict.Add(SuperbElvenOutridersBoots.DisplayName, new SuperbElvenOutridersBoots(1));
            dict.Add(SuperbElvenOutridersGloves.DisplayName, new SuperbElvenOutridersGloves(1));
            dict.Add(SuperbElvenOutridersLeggings.DisplayName, new SuperbElvenOutridersLeggings(1));
            dict.Add(SuperbElvenOutridersShoulderGuards.DisplayName, new SuperbElvenOutridersShoulderGuards(1));
            dict.Add(SuperbElvenTravellersArmour.DisplayName, new SuperbElvenTravellersArmour(1));
            dict.Add(SuperbElvenTravellersGloves.DisplayName, new SuperbElvenTravellersGloves(1));
            dict.Add(SuperbElvenTravellersLeggings.DisplayName, new SuperbElvenTravellersLeggings(1));
            dict.Add(SuperbElvenTravellersShoes.DisplayName, new SuperbElvenTravellersShoes(1));
            dict.Add(SuperbElvenTravellersShoulderGuards.DisplayName, new SuperbElvenTravellersShoulderGuards(1));
            dict.Add(SuperbOutridersArmour.DisplayName, new SuperbOutridersArmour(1));
            dict.Add(SuperbOutridersGloves.DisplayName, new SuperbOutridersGloves(1));
            dict.Add(SuperbOutridersLeggings.DisplayName, new SuperbOutridersLeggings(1));
            dict.Add(SuperbOutridersShoes.DisplayName, new SuperbOutridersShoes(1));
            dict.Add(SuperbOutridersShoulderGuards.DisplayName, new SuperbOutridersShoulderGuards(1));
            dict.Add(SuperbTravellersArmour.DisplayName, new SuperbTravellersArmour(1));
            dict.Add(SuperbTravellersCloak.DisplayName, new SuperbTravellersCloak(1));
            dict.Add(SuperbTravellersGloves.DisplayName, new SuperbTravellersGloves(1));
            dict.Add(SuperbTravellersHat.DisplayName, new SuperbTravellersHat(1));
            dict.Add(SuperbTravellersLeggings.DisplayName, new SuperbTravellersLeggings(1));
            dict.Add(SuperbTravellersRobe.DisplayName, new SuperbTravellersRobe(1));
            dict.Add(SuperbTravellersShoes.DisplayName, new SuperbTravellersShoes(1));
            dict.Add(SuperbTravellersShoulderGuards.DisplayName, new SuperbTravellersShoulderGuards(1));
            dict.Add(SwordswomanHeraldArmaments.DisplayName, new SwordswomanHeraldArmaments(1));
            dict.Add(TravellersArmour.DisplayName, new TravellersArmour(1));
            dict.Add(TravellersCap.DisplayName, new TravellersCap(1));
            dict.Add(TravellersCloak.DisplayName, new TravellersCloak(1));
            dict.Add(TravellersGloves.DisplayName, new TravellersGloves(1));
            dict.Add(TravellersLeggings.DisplayName, new TravellersLeggings(1));
            dict.Add(TravellersRobe.DisplayName, new TravellersRobe(1));
            dict.Add(TravellersShoes.DisplayName, new TravellersShoes(1));
            dict.Add(TravellersShoulderGuards.DisplayName, new TravellersShoulderGuards(1));
        }
    }
}